name: tutor_matchup
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1
  intl: ^0.19.0
  file_picker: ^8.1.2
  firebase_storage: ^12.3.2
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.1.1
  google_maps_flutter: ^2.9.0
  sliding_up_panel: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/tutormatchup_logo.png
    - assets/images/facebook_logo.png
    - assets/images/google_logo.png
    - assets/subjects.json
    - assets/TermsAndServices.json

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
